name: "Health Check"
author: "Adrian Torres"
description: "Assesses website health based on its status code to identify issues."
inputs:
  url:
    description: "Website URL"
    required: true
  alertCodesList:
    description: "HTTP status codes indicating issues, separated by spaces (e.g., '404 500 503')"
    required: true
    default: "304 404 405 429 500 502 503"
runs:
  using: "composite"
  steps:
    - name: Check Runner OS
      if: ${{ runner.os != 'Linux' }}
      shell: bash
      run: |
        echo "Supports Linux Only"
        exit 1

    - name: Set GitHub Path
      run: echo "$GITHUB_ACTION_PATH" >> $GITHUB_PATH
      shell: bash
      env:
        GITHUB_ACTION_PATH: ${{ github.action_path }}

    - name: Run health check
      run: health-check.sh $INPUT_URL
      shell: bash
      env:
        INPUT_URL: ${{ inputs.url }}
