name: 'Health Check'
description: 'Wepsite health according to status code'
inputs:
  url:
    description: 'Website url'
    required: true
runs:
    using: 'composite'
    steps:
      # - name: Check Runner OS
      #   if: ${{ runner.os != 'Linux' }}
      #   shell: bash
      #   run: |
      #     echo "Support Linux Only"
      #     exit 1

      # - name: Set GitHub Path
      #   run: echo "$GITHUB_ACTION_PATH" >> $GITHUB_PATH
      #   shell: bash
      #   env:
      #     GITHUB_ACTION_PATH: ${{ github.action_path }}

      # - name: Make health-check.sh executable
      #   run: chmod +x health-check.sh

      # - name: List files in the current directory
      #   run: ls -la
        
      - name: Run health check  
        run: echo "asdasdasdasd"
        shell: bash
        env:
          INPUT_URL: ${{ inputs.url }}
    
